//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits_Log
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SeansId { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual User User { get; set; }
    }
}
